"""
Shared database access for feature modules — SQLite locally, PostgreSQL
when DATABASE_URL is set (the cluster).

Write portable SQL and get connections from `connect()`:

- `?` placeholders (translated to `%s` for Postgres)
- `INSERT ... ON CONFLICT (...) DO UPDATE SET ...` / `INSERT OR IGNORE`
  (the latter becomes `ON CONFLICT DO NOTHING`)
- `CREATE TABLE IF NOT EXISTS`, TEXT / INTEGER / REAL columns
  (REAL becomes DOUBLE PRECISION — unix timestamps don't fit in float4)
- `INTEGER PRIMARY KEY [AUTOINCREMENT]` → an identity column
- need a new row's id? use `INSERT ... RETURNING id` (works on both)
- PRAGMA statements are ignored on Postgres

Rows support both `row["col"]` and `row[0]`. Catch `db.IntegrityError`
rather than the driver-specific class.
"""
from __future__ import annotations

import re
import sqlite3
from typing import Any, Iterable, Optional, Sequence

from backend.config import settings

try:  # psycopg2 is in requirements; only imported for real when used
    import psycopg2
    import psycopg2.extras

    IntegrityError: tuple[type[Exception], ...] = (
        sqlite3.IntegrityError,
        psycopg2.IntegrityError,
    )
except ImportError:  # pragma: no cover
    psycopg2 = None  # type: ignore[assignment]
    IntegrityError = (sqlite3.IntegrityError,)


def is_postgres() -> bool:
    return settings.database_url.startswith(("postgres://", "postgresql://"))


def connect():
    """Connection to the app database with dict-style rows.

    Use as a context manager for a transaction (commits on success, rolls
    back on error, does not close — same as sqlite3):
        with connect() as conn:
            conn.execute("...", (a, b))
    """
    if is_postgres():
        return PgConnection(settings.database_url)
    settings.db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(settings.db_path, timeout=30)
    conn.row_factory = sqlite3.Row
    return conn


# ---------------------------------------------------------------------------
# SQL translation (SQLite dialect → PostgreSQL)
# ---------------------------------------------------------------------------

_DDL_RE = re.compile(r"^\s*(CREATE|ALTER)\b", re.I)
_IDENTITY_RE = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY(\s+AUTOINCREMENT)?\b", re.I)
_REAL_RE = re.compile(r"\bREAL\b", re.I)
_OR_IGNORE_RE = re.compile(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", re.I)
_OR_REPLACE_RE = re.compile(r"^\s*INSERT\s+OR\s+REPLACE\b", re.I)
_PRAGMA_RE = re.compile(r"^\s*PRAGMA\b", re.I)


def _placeholders(sql: str) -> str:
    """`?` → `%s` and `%` → `%%` outside quoted strings / identifiers."""
    out: list[str] = []
    quote: Optional[str] = None
    for ch in sql:
        if quote:
            out.append("%%" if ch == "%" else ch)
            if ch == quote:
                quote = None
            continue
        if ch in ("'", '"'):
            quote = ch
            out.append(ch)
        elif ch == "?":
            out.append("%s")
        elif ch == "%":
            out.append("%%")
        else:
            out.append(ch)
    return "".join(out)


def translate(sql: str) -> Optional[str]:
    """SQLite-flavoured SQL → PostgreSQL. Returns None for no-op statements."""
    if _PRAGMA_RE.match(sql):
        return None
    if _OR_REPLACE_RE.match(sql):
        raise NotImplementedError(
            "INSERT OR REPLACE has no portable equivalent — use "
            "INSERT ... ON CONFLICT (...) DO UPDATE SET ..."
        )
    if _DDL_RE.match(sql):
        sql = _IDENTITY_RE.sub("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
        sql = _REAL_RE.sub("DOUBLE PRECISION", sql)
    if _OR_IGNORE_RE.match(sql):
        sql = _OR_IGNORE_RE.sub("INSERT INTO", sql)
        body = sql.rstrip().rstrip(";")
        if not re.search(r"\bON\s+CONFLICT\b", body, re.I):
            # RETURNING must stay last
            m = re.search(r"\bRETURNING\b", body, re.I)
            if m:
                body = body[: m.start()] + "ON CONFLICT DO NOTHING " + body[m.start():]
            else:
                body += " ON CONFLICT DO NOTHING"
        sql = body
    return _placeholders(sql)


def split_script(script: str) -> list[str]:
    """Split an executescript() body into statements (no `;` inside strings)."""
    return [s.strip() for s in script.split(";") if s.strip()]


# ---------------------------------------------------------------------------
# psycopg2 wrapper with the sqlite3 connection surface the codebase uses
# ---------------------------------------------------------------------------

class _NullCursor:
    rowcount = 0
    lastrowid = None

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


class PgCursor:
    def __init__(self, cur):
        self._cur = cur

    @property
    def rowcount(self) -> int:
        return self._cur.rowcount

    @property
    def lastrowid(self):
        raise AttributeError("lastrowid is not portable — use INSERT ... RETURNING id")

    @property
    def description(self):
        return self._cur.description

    def fetchone(self):
        return self._cur.fetchone() if self._cur.description else None

    def fetchall(self):
        return self._cur.fetchall() if self._cur.description else []

    def __iter__(self):
        return iter(self.fetchall())


class PgConnection:
    """Enough of sqlite3.Connection for this codebase, backed by psycopg2."""

    def __init__(self, dsn: str):
        if psycopg2 is None:  # pragma: no cover
            raise RuntimeError("psycopg2 is required for DATABASE_URL=postgres://...")
        self._conn = psycopg2.connect(dsn)
        # Accepted for compatibility with code that sets sqlite3.Row
        self.row_factory = None

    def cursor(self):
        return self._conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    def execute(self, sql: str, params: Sequence[Any] | dict = ()):
        pg_sql = translate(sql)
        if pg_sql is None:
            return _NullCursor()
        cur = self.cursor()
        cur.execute(pg_sql, tuple(params) if not isinstance(params, dict) else params)
        return PgCursor(cur)

    def executemany(self, sql: str, seq: Iterable[Sequence[Any]]):
        pg_sql = translate(sql)
        if pg_sql is None:
            return _NullCursor()
        cur = self.cursor()
        psycopg2.extras.execute_batch(cur, pg_sql, [tuple(p) for p in seq], page_size=500)
        return PgCursor(cur)

    def executescript(self, script: str) -> None:
        for stmt in split_script(script):
            self.execute(stmt)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is None:
            self._conn.commit()
        else:
            self._conn.rollback()
        return False
