"""backend/db.py — SQLite→Postgres translation and the portable connection."""
import os

import pytest

from backend.db import translate


@pytest.mark.parametrize(
    "sqlite_sql,pg_sql",
    [
        ("SELECT * FROM t WHERE a = ? AND b = ?", "SELECT * FROM t WHERE a = %s AND b = %s"),
        ("SELECT '?' , x FROM t WHERE y = ?", "SELECT '?' , x FROM t WHERE y = %s"),
        ("SELECT * FROM t WHERE name LIKE 'a%' AND x = ?", "SELECT * FROM t WHERE name LIKE 'a%%' AND x = %s"),
        (
            "CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY AUTOINCREMENT, ts REAL, n INTEGER)",
            "CREATE TABLE IF NOT EXISTS t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts DOUBLE PRECISION, n INTEGER)",
        ),
        ("INSERT OR IGNORE INTO t (a) VALUES (?)", "INSERT INTO t (a) VALUES (%s) ON CONFLICT DO NOTHING"),
        (
            "INSERT OR IGNORE INTO t (a) VALUES (?) RETURNING id",
            "INSERT INTO t (a) VALUES (%s) ON CONFLICT DO NOTHING RETURNING id",
        ),
        # REAL only rewritten in DDL — a value 'REAL' in DML stays put
        ("SELECT 'REAL' FROM t", "SELECT 'REAL' FROM t"),
    ],
)
def test_translate(sqlite_sql, pg_sql):
    assert translate(sqlite_sql) == pg_sql


def test_pragma_is_noop():
    assert translate("PRAGMA journal_mode=WAL") is None


def test_insert_or_replace_rejected():
    with pytest.raises(NotImplementedError):
        translate("INSERT OR REPLACE INTO t VALUES (?)")


PG_URL = os.environ.get("TEST_DATABASE_URL", "")


@pytest.mark.skipif(not PG_URL.startswith("postgres"), reason="set TEST_DATABASE_URL to run")
def test_pg_roundtrip(monkeypatch):
    from backend import db
    from backend.config import settings

    monkeypatch.setattr(settings, "database_url", PG_URL)
    with db.connect() as conn:
        conn.execute("DROP TABLE IF EXISTS db_test_t")
        conn.execute(
            "CREATE TABLE IF NOT EXISTS db_test_t (id INTEGER PRIMARY KEY AUTOINCREMENT, "
            "name TEXT UNIQUE, ts REAL)"
        )
        new_id = conn.execute(
            "INSERT INTO db_test_t (name, ts) VALUES (?, ?) RETURNING id", ("a", 1791000000.25)
        ).fetchone()[0]
        conn.execute("INSERT OR IGNORE INTO db_test_t (name, ts) VALUES (?, ?)", ("a", 2.0))
        conn.execute(
            "INSERT INTO db_test_t (name, ts) VALUES (?, ?) "
            "ON CONFLICT (name) DO UPDATE SET ts = excluded.ts",
            ("b", 3.5),
        )
        conn.execute("PRAGMA foreign_keys=ON")
    with db.connect() as conn:
        rows = conn.execute("SELECT id, name, ts FROM db_test_t ORDER BY name").fetchall()
        assert [(r["name"], r["ts"]) for r in rows] == [("a", 1791000000.25), ("b", 3.5)]
        assert rows[0][0] == new_id
        assert conn.execute("SELECT count(*) FROM db_test_t WHERE name LIKE 'a%'").fetchone()[0] == 1
        with pytest.raises(db.IntegrityError):
            conn.execute("INSERT INTO db_test_t (name) VALUES (?)", ("a",))
    with db.connect() as conn:
        conn.execute("DROP TABLE db_test_t")
