---
- name: Install base packages
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
      - ca-certificates
      - curl
      - git
      - python3-docker      # required by community.docker modules
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
